/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloArgs */

#ifndef _Included_HelloArgs
#define _Included_HelloArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloArgs
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloArgs_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
